// Arte ASCII dos pokemon, no estilo dos logos que o neofetch imprime.
//
// Silhueta derivada dos sprites oficiais por cobertura de celula: a borda usa
// caractere leve (. : - = + o) simulando antialiasing e o miolo e chapado, com
// um caractere por faixa de cor (M d s O, do mais denso ao mais leve). As cores
// sao as do proprio sprite — media entre elas devolvia tons lamacentos —, so
// clareadas ate um piso de luminancia para nao sumirem no fundo do terminal.
//
// O gengar e a excecao: o rosto dele foi desenhado a mao. Conversao automatica
// nao resolve olhos e dentes nesta escala, e o rosto e a identidade dele.
//
// Marcadores de cor no formato do proprio neofetch: ${c1} vale dali em diante,
// ate o proximo marcador, inclusive atravessando linhas. Cada pokemon tem a
// sua propria paleta em `colors`, onde c1 e o primeiro item.
//
// Aspas simples de proposito: numa template string a crase encerraria a string.
// Nenhuma arte tem crase nem barra invertida — mantenha assim se editar.

export const POKEMON = {
  bulbasaur: {
    dex: 1,
    colors: ['#505050', '#399494', '#62D5B4', '#83EEC5'],
    lines: [
      '                                        ${c1}...+M...',
      '                           .::::::::::::MMMM${c3}s${c1}MMM:.',
      '                        ===o${c4}OOOOOOOOO${c3}sssss${c1}MM${c3}s${c1}MMMM+',
      '                      :+${c4}OOOOOOOOOOOOOOO${c1}MMM${c3}sss${c1}MMMM+',
      '   ${c2}..${c1}MMM.... ${c2}........${c1}MM${c4}OOOOOOOO${c1}MMMMMMM${c4}OO${c3}sssss${c1}MMMM+..',
      '   ${c2}+d${c4}OOO${c1}MMM${c2}=-dddddddddddddd${c1}MMM${c4}OO${c3}ss${c1}M${c4}OOOOOOO${c3}sssss${c1}MMMM=-',
      '   ${c2}+d${c4}OO${c2}d${c4}OOOOOOOO${c2}ddddd${c4}O${c3}ssss${c4}OOOOO${c3}sss${c1}M${c4}OOOOOOO${c3}sssss${c1}MMMMMM',
      '   ${c2}+dd${c4}OOOOOOOOO${c2}dddddd${c4}OOO${c3}ssssssssss${c2}d${c1}MM${c4}OOOOO${c3}sssss${c1}MMMMMMo-',
      '   ${c2}+d${c4}OOOOOOOO${c2}dddddd${c4}OOOOO${c3}ssssssssss${c2}d${c1}MM${c4}OOO${c3}ssssss${c1}MMMMMMMM=.',
      ' ${c2}.-od${c4}OOOOOOOO${c2}dddd${c4}OOOOOOO${c3}s${c2}dddd${c3}ssss${c2}ddd${c1}M${c4}O${c3}sssssss${c1}MMMMMMMMMMM',
      ' .MMM${c2}d${c4}OO${c3}ss${c4}OOOOO${c2}ddd${c4}O${c3}ss${c4}OO${c2}d${c1}MMM${c4}OOO${c1}MM${c2}ddddd${c1}MMMMMMMMMMMMMMMMMMM',
      '${c2}.${c1}:MMM${c2}dd${c4}O${c3}ss${c4}OOO${c2}ddddd${c4}O${c3}ss${c4}O${c2}dd${c1}MMM${c4}OOOO${c1}M${c2}ddddd${c1}MMMMMMMMMMMMMMMMMMM',
      '${c2}dd${c4}O${c1}MM${c4}OO${c2}d${c4}OOOOO${c2}ddd${c4}OOOOO${c2}dd${c1}M${c4}OO${c1}MMM${c4}OOO${c2}ddddd${c1}M${c2}dd${c1}MMMMMMMMMMMMMM+=',
      '${c2}dd${c3}s${c1}MMM${c2}dd${c3}sssssssssssss${c2}dd${c1}MMMMMM${c4}OO${c2}dddddddddddd${c1}MMMMMMMMMMM-',
      'MMM${c3}ssssssssssssssssssssssssss${c2}ddd${c1}MM${c2}dddddddddddd${c1}MMMMMMM..',
      'oo${c2}d${c1}MMMM${c3}sss${c2}d${c3}ssss${c2}d${c3}ssssssssss${c2}d${c1}MMMMM${c2}dddddddddd${c1}MMM${c2}ddd${c1}MMM.',
      ' .=${c2}od${c4}O${c2}d${c1}MMM${c3}ssssssss${c2}d${c1}MMMMMMM${c4}O${c2}dddddddd${c1}MM${c2}ddddd${c1}MMMMM${c2}ddd${c1}M-:',
      '   .:MMM${c2}ddddd${c1}MMMMMMMMMM${c2}dddddddd${c1}MMM${c2}ddddddddddddddddd${c1}MM',
      '     ...MMM${c2}ddddddddddddddd${c1}MMMM${c2}dddddddddd${c1}MM${c2}ddddd${c1}M${c2}ddddd${c1}o-',
      '        MM${c2}d${c1}MMMMMMMMMMMMMMM${c2}ddddddddd${c1}MM${c2}ddd${c1}MM${c2}ddd${c1}MMMMM${c2}ddd${c1}M-',
      '        ${c2}==${c3}sssss${c2}d${c1}MM${c2}ddddddddd${c1}MM${c3}sss${c2}ddddd${c1}MMM${c2}ddddd${c1}MMMMM${c2}ddd${c1}M-',
      '         ${c2}.ddd${c3}sss${c2}ddddd${c1}MMMMMM${c2}ddddd${c3}ss${c2}ddd${c1}MMM${c2}dddddd${c1}MM${c2}dddd${c1}M:.',
      '         ${c2}.o${c3}sssssss${c2}ddd${c1}M-..${c2}:d${c3}ss${c2}ddd${c3}ss${c2}ddd${c1}o-.MM${c2}ddddddddd${c1}oo',
      '         .:${c2}+d${c3}ss${c2}d${c3}ss${c2}ddd${c1}+:  ${c2}.d${c3}sssssss${c2}d${c1}MM   ++${c4}O${c1}MM${c4}O${c1}MM${c4}OO${c1}+.',
      '         .-o${c4}O${c1}MM${c4}O${c1}MM${c2}d${c1}=-   -=MM${c3}s${c2}dd${c3}s${c2}ddd${c1}=-    .-------:',
      '           .........    .-MMMMMMM+..',
    ],
  },
  charmander: {
    dex: 4,
    colors: ['#505050', '#BD3800', '#DE5239', '#FF9441'],
    lines: [
      '          ${c3}...=ss${c2}dddd+...',
      '         ${c3}-+ss${c4}OOOOOOOO${c2}ddo${c1}-.',
      '       ${c3}:+${c4}OOOOOOOOOOOOOOO${c1}M.',
      '      ${c3}.=s${c4}OOOOOOOOOOOOOOOO${c1}M+',
      '      ${c3}ss${c4}OOOOOOOOOOOOOOOOO${c1}Mo-',
      '      M${c3}ss${c4}OOOOOOOOO${c3}s${c4}OO${c1}MMM${c3}sss${c1}M',
      '      MM${c3}s${c4}OOOOOOOOOO${c1}MMMMM${c2}d${c3}ss${c1}M',
      '      M${c4}OOOOOOOOOOOOOO${c1}MMM${c2}d${c3}ss${c1}M                   ${c2}::',
      '    -o${c1}M${c4}OOOOOOOOOOOO${c2}dd${c1}MMM${c3}sss${c1}M                   ${c2}+d${c4}o.',
      '    ${c2}-d${c4}OOOOOOOOOOOOOO${c3}sssssss${c1}M                 ${c2}.:+${c4}OO.',
      '    ${c2}.:d${c4}OOOOOOOOOOO${c3}s${c2}ddd${c3}ssss${c1}+:       ${c2}:==:      .d${c4}OOO+-',
      ' ${c2}.... ${c1}ooo${c4}OOOOOO${c2}ddd${c1}M${c4}OO${c3}ssss${c1}M+${c2}..-oooood${c3}s${c1}M-      ${c2}.d${c4}OOOOO${c2}o.',
      ' -dd=::::${c1}MMMMM${c2}ddddd${c3}ssssss${c2}dddd${c4}OOOOOO${c3}ss${c1}M=:    ${c2}.-dddd${c4}OOO${c2}-.',
      ' ${c1}-M${c3}ss${c4}OOOO${c3}s${c1}MMM${c4}OOO${c3}ss${c1}MMM${c3}sssss${c4}OOOO${c3}ssssss${c1}MM=:    ${c2}+dddddd${c4}OOOo${c2}=',
      '${c1}+o${c3}ssss${c4}OOO${c3}ssss${c1}MMMMM${c3}ssssssssssssssss${c1}o-...     ${c2}+d${c4}OOO${c2}d${c4}OOOOO${c2}d',
      ' ${c1}.--+${c3}ssssssssssssssssssssssssss${c1}---          ${c2}+d${c4}OOOOOOOOO${c2}d',
      '    ${c1}...=MM${c3}sss${c2}dd${c4}OOOOOOO${c3}sss${c4}OOO${c1}M=.             ${c2}.-d${c4}OO${c2}d${c4}OOO${c2}ddd',
      '          ${c1}:+${c2}d${c3}ss${c4}OOOOOOOOOOOOO${c1}M=.                ${c2}-+dddd+-',
      '            d${c4}OOOOOOOOOOOOOOO${c3}s${c1}MM                 ${c2}.dddd.',
      '            d${c4}OOOOOOOOOOOOOOOOOO${c1}+:               ${c2}.d${c4}OO${c1}M.',
      '          ${c2}-d${c4}OOOOOOOOOOOOOOOOOOO${c1}M-           ${c2}...+d${c4}OOO${c1}M.',
      '         ${c2}-+d${c4}OOOOOOOOOOOOOOOOOOO${c1}M+-      ${c2}----odd${c4}OOO${c3}s${c1}o-.',
      '       ${c2}:+${c4}OO${c3}s${c4}OOOOOOOOOOOOO${c3}ss${c4}OOOOOO${c3}s${c1}++${c2}++++${c4}OOOOOOO${c3}ss${c4}O${c1}M+',
      '      :${c2}=d${c4}OOO${c3}s${c4}OOOOOOOOOOO${c3}s${c4}OOOOOOOOO${c1}MM${c3}ssssss${c4}OO${c3}ss${c4}OOo${c1}=.',
      '      MM${c4}OOOOOOOOOOOOOOOO${c3}s${c4}OOOOOOOO${c3}sss${c1}M${c3}sssss${c4}OOOO${c1}M-.',
      '      oM${c4}OOOOO${c3}ss${c1}M${c4}OOOOOOOO${c2}d${c3}ss${c4}OOOO${c3}sssss${c1}M${c4}OOOOOO${c1}oo=..',
      '       :=${c4}OOO${c3}sssss${c1}MM${c4}OOOOO${c2}d${c3}ssssssssss${c1}MM${c4}OOO${c2}==-',
      '         ${c1}MM${c3}ssssss${c1}MM-:::::${c2}:-d${c3}ssssss${c1}M=${c2}::::',
      '      ${c1}.-o${c3}sssssss${c1}o=..      ${c2}.d${c4}OOOO${c3}ss${c1}M-.',
      '      =+${c4}O${c2}d${c1}M${c4}O${c3}sso${c1}=.         ${c2}.=${c3}s${c4}OOOOO${c3}ss${c1}M:.',
      '       .::::::.             :=MMMMMMM:.',
    ],
  },
  charizard: {
    dex: 6,
    colors: ['#0C6079', '#505050', '#CD5241', '#EE8329'],
    lines: [
      '                  ${c3}-+.--.',
      '                  .=sss+..',
      '                ${c2}:. ${c3}.os${c4}OOO${c3}+-+   ${c2}.-+:',
      '              :o${c4}O${c2}o.${c3}.-o${c4}OOOO${c3}ss=..${c2}.+${c4}OO${c3}o:${c2}..-====..',
      '       ..-${c4}oo${c2}-=${c4}OOO${c2}- ${c3}.s${c4}OOOO${c3}ss${c4}O${c3}ss: ${c2}.+${c4}OOOOOOOOOOOOo${c3}--..',
      '      ${c2}:${c4}+OOOOOOOO${c2}+  ${c3}.-${c4}oOOOOOO${c3}s=   ${c2}.o${c4}OO${c1}MMMMMMMMMMM${c4}OOO${c3}-${c2}.',
      '   .=${c4}oO${c1}MMMMMMM${c4}OO${c2}o:  ${c3}:ss${c4}OOOO${c3}-:     ${c2}o${c4}O${c1}MMMMMMMMMMMMMM${c4}OO${c3}-',
      '   ${c2}o${c3}s${c1}MMMMMMMMMM${c2}d${c4}O${c2}-.  ${c3}..${c2}=${c4}OO${c3}=.      ${c2}o${c4}O${c1}MMMMMMMMMMMMMMM${c4}O${c3}s${c2}.',
      '  -${c3}s${c1}MMMMMMMMMMMMM${c4}O${c2}.     -${c4}O${c3}s+${c2}:    -${c4}OO${c1}MMMMMMMMMMMMMMMM${c4}O${c3}+',
      '${c2}.-${c3}ss${c1}MMM${c2}d${c3}s${c2}d${c1}MMMMMMM${c4}O${c2}d.     -${c3}osss+${c2}=:o${c3}s${c1}MMMMMMMMMMMMMMMMM${c3}s${c4}O${c3}-',
      '${c2}o${c3}s${c1}MMMM${c2}d${c3}ss${c2}=${c1}MM${c4}OOO${c2}d${c1}MM${c3}ss${c2}=-.   .:${c3}osssss${c1}MMMMMMMMMMMMMMMMMMM${c4}OO${c2}:',
      'd${c3}s${c1}MMMM${c3}ss${c2}d+${c4}+OO${c2}+.${c1}.+MMM${c3}ss${c2}d:    +${c4}OO${c3}s${c1}MMMMMMMMMMMMMMM=+MMMMM${c3}s${c2}d',
      '.+${c1}MMM${c4}OOOOOOO${c2}d-.-+${c4}OOOOOOO${c2}d=-+${c3}ss${c2}d${c1}MMMMMMMMMMMMMM=.  ${c2}.${c1}+MMMM${c2}d',
      ' .+${c4}OOOOOOOOOOO${c3}ssss${c4}OOOOOOOOOOO${c1}MMMMMM+..${c2}=${c3}ssss${c1}MM${c2}+.   .d${c1}MMM${c2}d',
      ' .o${c4}O${c3}s${c4}OOOOOOOOOO${c3}ss+${c2}=+${c3}sss${c4}OOOOOOO${c2}ddd${c1}M${c2}=    .=${c3}ssssss${c2}=.  :${c1}oMM${c2}d',
      '  .+d${c3}s${c4}O${c2}d${c4}OOO${c2}dd${c4}OO${c2}d.-${c3}ossssss${c4}OOOOOOOOOOo${c2}==....+${c3}ssssss${c2}+  +${c1}M${c3}o.',
      '  ${c2}:${c4}+OOOOOO${c3}ss${c2}dd${c3}s${c2}d${c3}ssssssss${c4}OOOOOOOOOOOOOOO${c3}s${c2}+ .=${c3}ssssss${c2}=.:${c3}o${c2}.',
      '.-${c4}oOOOOo${c2}::${c3}sss${c2}d${c3}s${c2}+${c3}+s${c2}d${c3}s${c4}OOOOOOOOOOOOO${c3}sso${c2}=:${c3}ss${c2}d.  d${c3}ssssss${c2}=..',
      '.-${c4}+OO${c3}+${c2}++${c3}.${c2}=d${c3}s${c2}ddo..+${c4}OOOOOOOOOOOOOOOOO${c3}ss${c2}d${c3}sss${c2}= -${c3}ssssssss${c2}-',
      '   ..:+${c3}sss${c4}O${c2}dd=. o${c4}OOOOOOOOOOOOOOOOO${c2}d${c4}OOOOO${c3}s${c2}++${c4}OOOOOO${c3}sss${c2}d',
      '     .=${c3}ss${c2}d=${c3}os${c2}: -${c4}OOOOOOOOOOOOOOOOOOO${c3}s${c2}d${c4}OOO${c3}ss${c2}d${c4}OOOOO${c3}ssss${c2}d',
      '      .:=+- .:${c4}+OOOOOOOOOOOOOOOOOOOOOO${c2}d${c3}s${c2}dddd${c4}O${c3}sssssss${c2}o.',
      '            ${c3}-${c4}OOOOOOOOOOOOOOOOOOOOOOOOOOO${c3}ss${c2}d${c3}ssssss${c4}O${c2}+.',
      '           .${c3}s${c4}OOOOOOOOOOOOOOOOOOO${c2}d${c4}OOOOOOOO${c3}ssss${c4}OOO+${c2}:',
      '           =${c4}OOOOOO${c3}ss${c4}OOOOOOOOOOOO${c2}d${c3}s${c4}OOOOOOO${c3}ss${c2}d${c4}O+${c2}-.',
      '           :${c3}sssssssss${c2}oo${c4}oOOOOOOOO${c2}d${c3}ssss${c4}O${c3}ssssss${c2}-',
      '            .${c3}+ssssss${c2}+.  ..-==dd${c4}OO${c2}d+${c3}sssssssss${c2}+',
      '            .:+d${c4}O${c2}d${c3}sss${c2}+             .+${c3}sssss${c4}O${c3}ss${c2}-',
      '            .=o${c4}o${c2}=oo--.              -d${c3}ssss${c4}O${c3}s${c4}O${c2}+.',
      '                                     .:${c4}o${c2}o:${c4}+O${c2}==.',
    ],
  },
  squirtle: {
    dex: 7,
    colors: ['#505050', '#297383', '#5A9CA4', '#8BC5CD'],
    lines: [
      '             ${c3}...+sssss${c2}ddd-..',
      '            ${c3}-+ss${c4}OOOOOOOOOO${c2}dd-.',
      '          :+${c4}OOOOOOOOOOOOOOOOO${c2}o+',
      '         dd${c4}OOOOOOOOOOOOOOOOOOOO${c2}d-',
      '       .-d${c4}OOOOOOOOOOO${c3}ss${c4}OOOOOOOO${c2}d+-',
      '       -d${c1}M${c4}OOOOOOOOOOO${c3}s${c1}MM${c4}OOO${c3}s${c4}OO${c3}sss${c1}M',
      '       ${c2}-d${c4}O${c3}ss${c4}OOOOOOOOO${c1}MMMM${c4}OO${c2}d${c3}sssss${c1}M',
      '       ${c2}-d${c1}MM${c3}s${c4}OOOOOOOOO${c1}MMMM${c4}OO${c2}d${c3}sssss${c1}M',
      '      ${c2}+o${c4}OOOOOOOOOOOOO${c1}MMMM${c4}OO${c3}ssssss${c1}M',
      '      +o${c4}OOO${c3}s${c4}OO${c3}s${c4}OOOOOOOOO${c3}ssssssss${c1}o+ ${c3}..${c2}.....',
      ' ${c3}.- .- ${c1}.-${c2}d${c1}M${c4}OOOOOOOOOOO${c2}d${c3}ss${c1}M${c2}d${c3}ssss${c1}M- ${c3}-+s${c2}dddd${c1}=:',
      ' ${c2}-d${c4}+${c3}os${c2}++${c1}+MM${c3}s${c1}MMMMMMMMMMMMM${c3}sssss${c1}M${c3}so${c4}+OOO${c2}d${c3}ss${c1}M-.',
      '${c3}s${c4}OOOOOOO${c3}sss${c1}M${c3}sss${c1}MMMMMMM${c3}sssss${c2}d${c1}MM${c2}d${c4}OOOOO${c2}dd${c3}ss${c1}+:',
      '${c2}-+${c4}OOOOOOOOOO${c1}M${c3}s${c2}d${c3}ssssssss${c1}MMMMM${c4}OO${c3}s${c4}OOOO${c3}ssss${c1}M',
      ' ${c2}..o${c3}sssssssss${c1}MM${c4}OOOOOOOOOOOO${c2}d${c3}s${c4}OOOO${c3}ssss${c1}M=.     ${c2}.......',
      '    :==+${c3}ssss${c1}MMM${c4}OOOOOO${c1}MMMMMM${c2}d${c3}sssssss${c1}MMM=:  ${c2}.::-ddddd+:.',
      '       ${c1}.::=M${c4}OOOOOOOOOOOOOOO${c1}M${c4}OO${c1}MMMM${c4}O${c1}MMMMM ${c2}:+${c3}s${c4}OOOOOOOO${c3}s${c2}+-',
      '          ${c1}-M${c4}OOOOOOOOOOOOOOOOOOO${c1}MM${c4}OOO${c1}MMMM${c2}o${c3}ss${c4}OOOOOOOOOO${c2}d+${c1}.',
      '          -M${c4}OOOOOOOOOOOOO${c1}M${c4}OOOOO${c1}MM${c4}OOO${c1}MMMM${c3}sssss${c4}OO${c2}ddd${c4}OOO${c3}ss${c1}M',
      '          -M${c4}OOO${c1}MMMM${c4}OOOO${c1}MM${c4}OOOOOO${c1}MMM${c4}OO${c3}s${c1}MMM${c3}sssss${c2}d${c3}s${c4}OOOOO${c3}sss${c1}M',
      '         ${c3}.${c1}-M${c4}OOOO${c1}MM${c4}OOOOOOO${c1}MM${c4}OOOO${c1}MMM${c4}OOO${c1}MMM${c3}ssss${c1}MM${c3}sssssss${c1}M+.',
      '       ${c3}.:s${c4}O${c1}M${c4}OOOOOOOOOOOOOOO${c1}M${c4}OO${c3}ss${c4}O${c2}ddd${c4}O${c1}MMM${c3}sssss${c1}M${c3}sssssss${c1}+-',
      '      ${c3}=+${c4}OOOO${c1}M${c4}OOOO${c1}MM${c4}OOOOOOOO${c3}s${c4}OOOOOOO${c3}ss${c2}dd${c3}ssssssss${c1}MMMM+:.',
      '      ${c3}s${c4}OOOOOO${c1}MMM${c4}OOO${c1}MMM${c4}OOOOO${c2}d${c4}OOOOOOOO${c3}s${c1}M${c3}ssssss${c1}oooo=...',
      '      ${c2}dd${c4}OOOOO${c3}ss${c1}M${c4}OOOOOOO${c1}MMMM${c2}d${c4}OOOOOOO${c3}ss${c2}d${c1}MM====.',
      '      :=M${c3}ssssssss${c1}MMMMMMMMMMM${c2}d${c3}ssssssssss${c1}M',
      '      ${c2}.-d${c3}sssssss${c1}MMo:........o${c3}ssssssssss${c1}M..',
      '      ${c2}=+${c4}O${c3}s+${c2}=${c4}O${c3}so${c1}==-           -M${c3}sssssssss${c1}M:',
      '       .::. ::.              .:MMM:=MM=::.',
    ],
  },
  pikachu: {
    dex: 25,
    colors: ['#505050', '#9C5200', '#F6BD20', '#F6E652'],
    lines: [
      '   ${c1}.=+..',
      '   MMMM.',
      ' ..MMMM+=',
      ' -MMMMMM+',
      ' -MMMM${c3}s${c2}d+                        ${c1}-=====',
      ' -MM${c3}sssss${c2}o.               ..${c1}:ooooMMMMMMoo=',
      ' -M${c3}ssssss${c2}d.  -------.  ---dd${c4}O${c3}s${c4}OOO${c1}MMMMMMM=:',
      ' ..${c2}d${c3}sssss${c2}d++${c3}+${c4}OOOOOOO${c3}++${c2}+${c4}OOOOOOOOO${c1}MMMMMMM..',
      '   ${c2}=+${c3}sssss${c4}OOOOOOOOOOOOOOOOOOOOOO${c1}MM+==:        ${c2}:=dd=.',
      '    -d${c4}OOOOOOOOOOOO${c3}s${c1}MMM${c3}s${c4}OOO${c3}s${c4}O${c2}d${c1}M-:::.         ${c2}.=${c4}OOOOOo${c2}=.',
      '   od${c3}s${c1}M${c3}ss${c4}OOOOOOOO${c1}MM${c4}O${c1}MMM${c4}OOOO${c1}M+..          ${c3}..+${c4}OOOOOOOO${c2}d:.',
      '   dd${c1}M${c4}OOOOOOOOOOO${c1}MMMMMM${c4}OOOOO${c1}+          ${c3}--=s${c4}OOOOOOOOOO${c2}d+',
      '   dd${c1}M${c2}d${c4}OOOOOOOOOOOOOOOO${c2}ddd${c4}O${c3}ss${c2}+.      :+${c4}OOOOOOOOOOOOOO${c2}d+',
      ' -d${c4}OOOOOOO${c2}ddd${c3}ss${c4}OOOOOOO${c2}ddddd${c3}ss${c1}M.   ${c2}.:d${c4}OOOOOOOOOOOOOOOOOO${c2}d',
      ' -ddd${c3}sssssssssssssssss${c2}ddddd${c3}ss${c1}M.   ${c2}-d${c3}s${c4}OOOOOOOOOOOOOOOOOO${c2}d',
      ' -odd${c3}ssssssssssssssssss${c2}ddd${c3}sss${c1}M.${c2}..+${c3}ssssss${c4}OOOOOOOOOOOOO${c1}o=${c2}.',
      '   -+${c3}ssssssssssssssssssssssss${c1}M.${c2}.d${c3}sssssssssss${c4}OOOOOO${c1}+--.',
      '    -M${c3}sssssssssssssssssssssss${c4}O${c1}+=${c2}.+${c3}sssssssssss${c1}MM=...',
      '    -M${c4}O${c3}ssssssssssssssssssss${c4}OOO${c1}M+  ${c2}:+${c3}ssssss${c1}++-',
      '    -M${c4}OOOOOOO${c3}ssssssssss${c4}OOOOOOO${c1}M+    ${c2}-+d${c3}ss${c2}o-.',
      '   ${c1}.${c3}-s${c4}OOO${c2}d${c4}OOOOOOOOO${c3}s${c4}OOOOOOOOOO${c2}d+${c1}....o${c3}sssss${c2}d:.',
      '   ${c1}MM${c4}OOOO${c3}s${c4}OOOOOOOOO${c3}s${c4}OOOOOOOOOOOO${c1}M${c2}-${c1}+M${c3}sssssss${c2}d=',
      '   ${c1}MM${c3}s${c4}OOOO${c2}dd${c4}OOOOO${c2}dd${c4}OOOOOO${c3}ss${c4}OOO${c3}ss${c1}M${c3}ssssss${c2}dd+.${c1}..',
      '   MM${c2}d${c4}OOOO${c3}ss${c4}OOOO${c2}d${c4}OOOOOOOO${c2}d${c4}OOOO${c3}ss${c1}MMM${c3}sss${c1}M..',
      ' .-${c4}OOO${c2}d${c4}OO${c3}s${c4}O${c2}d${c4}OOOOO${c1}MM${c4}OOO${c2}d${c4}OOOOOO${c3}ssss${c1}M+-M${c2}ddd${c1}=:',
      '.${c2}-d${c4}OOOO${c2}ddd${c4}OOOOOOOOO${c2}ddd${c4}OOOOO${c3}ssssss${c1}MMo${c2}dddd${c1}o=',
      'MM${c3}s${c4}OOOOOOOOOOOOOOOOOOOOOO${c3}s${c4}O${c3}sssssss${c2}ddd${c1}+==.',
      'MM${c3}ssssss${c4}OOOOOOOOOOO${c3}ssss${c4}O${c3}ss${c4}O${c3}ssssssss${c1}M:.',
      ' ${c2}-d${c3}ssssssssssssssssssssssssssssss${c2}d-',
      ' ${c1}.-${c3}ssssssssssssssssssssssssssssss${c1}=.',
      '${c2}.-+dd${c3}s${c2}dddddd${c1}o......${c2}.${c1}+o${c2}oodd${c3}sss${c2}d${c1}M+:.',
      '${c2}=+${c4}O${c2}d${c1}M${c4}O${c3}s${c2}+=${c1}==:            ${c2}-d${c3}ssss${c2}dd${c1}M.',
      ' .::::${c2}:.                ${c1}.::+MMM+:.',
    ],
  },
  gengar: {
    dex: 94,
    colors: ['#A97FD0', '#FFF6FF', '#FF5A5A'],
    lines: [
      '                                          ${c1}.-++.',
      '                            --         .=sssss:',
      '                          -sss      .=sssssss+.',
      '   .-so--:     -s+.=s=. :sssss -ss=ssssssssss-',
      '   .-ssssssss+-+ssssssssssssssssssssssssssss-',
      '     .ssssssssssssssssssssssssssssssssssssss-',
      '      .=sssssssssssssssssssssssssssssssssss-',
      '        .ssssssssssssssssssssssssssssssssss-      :o=.',
      '  - .-   .=sssssssssssssssssssssssssssssss+.  :-+ssss---',
      ' ssssso-: .=sssssssssssssssssssssssssssssssssssssssssss-',
      '  sssssssssssss${c3}@@@${c1}ssssssssssssssssssss${c3}@@@${c1}sssssssssssss-.',
      '-sssssssssssss${c3}@@@@@@${c1}sssssssssssssss${c3}@@@@@@${c1}ssssssssssss.',
      ' --sssssssssss${c3}@@@@@@@${c1}ssssssssssss${c3}@@@@@@@${c1}sssssssssss=.',
      '   .-sssssssssss${c3}@@@@@@${c1}sssssssssss${c3}@@@@@@${c1}ssssssssss=.',
      '     .=ssssssssssss${c3}@@@${c1}sssssssssss${c3}@@@${c1}ssssssssssss:',
      '        .=ssssssssssssssssssssssssssssssssssssss:',
      '         .=ss${c2}MM${c1}ssssssssssssssssssssssssss${c2}MM${c1}sssss:',
      '          :sss${c2}MMMMMMMMMMMMMMMMMMMMMMMMMMMM${c1}ssssss:',
      '           :ssss${c2}sMsMsMsMsMsMsMsMsMsMsMsMs${c1}sssssss=.',
      '            :ssssss${c2}MMMMMMMMMMMMMMMMMM${c1}sssssssssssssss=.',
      '             -ssssssssssssssssssssssssssssssssssssss=.',
      '            .+ssssssssssssssssssssssssssssssssssss=.',
      '            :sssssssssssssssssssssssssssssssss=-.',
      '            .+ssssssssssssssssssssssssssssssss:',
      '             .+ssssssss=.-------.-ssssssssssss:',
      '             -ssssssss=.          .=sssssssss+.',
      '              .----.                .ssssssss-',
      '                                     .--=ss+-.',
    ],
  },
  eevee: {
    dex: 133,
    colors: ['#505050', '#A4624A', '#D59C4A', '#E6C594'],
    lines: [
      '             ${c1}..${c2}++${c1}..',
      '            .-M${c3}ss${c1}M.',
      '            +M${c2}d${c1}MM${c3}s${c1}+-',
      '          .o${c2}ddd${c1}MM${c3}s${c1}M+',
      '          .M${c2}dd${c1}MMM${c3}s${c1}M+                      ${c2}.::.',
      '          ${c1}.MMMMMM${c2}d${c1}M+                  ${c2}====+${c3}s${c1}M-',
      '         =o${c2}d${c1}MMMMM${c2}d${c1}M+               ${c2}ooo${c3}ssssss${c1}M-',
      '         +M${c2}d${c1}MMM${c2}dd${c1}M.           ..${c2}.=d${c3}sss${c2}d${c1}MMMM${c2}d${c1}+:',
      '         +M${c2}d${c1}MMM${c2}dd${c1}M.          -+M${c2}d${c3}ss${c2}d${c1}MMMMM${c2}dd${c1}M',
      '         .-MMM${c2}d${c1}M+..        -+${c3}sss${c1}MMMMMMMM${c2}d${c1}M=.',
      '          .MMMMM+.++... .-M${c2}dd${c3}s${c1}MMMMMMMMMM${c2}d${c1}+:',
      '         :=${c2}d${c1}M${c3}ssss${c1}M${c3}ss${c1}MMo-oM${c3}sss${c1}MMMMMMMMM${c2}d${c1}+-',
      '       .+${c3}sssssssss${c2}dd${c3}sss${c1}M${c3}ss${c2}d${c3}ss${c1}MMMMM${c2}dd${c1}MM:.          +++',
      '      =o${c3}sssssssssssssssssss${c1}MMMM${c2}dd${c1}Moo-.   ..${c3}.${c1}ooo${c3}oo${c4}oO${c1}MM',
      '    ${c2}.:${c1}+${c3}sssssssssssssssssss${c1}M${c2}ddd${c1}+==:     .:M${c4}O${c3}s${c4}OOOOO${c3}s${c2}d${c1}+=',
      '    ${c2}.d${c1}M${c3}sssssssssssssssssss${c2}ddd${c1}M-       =+${c4}OOOOOOO${c3}ss${c4}O${c1}M-',
      '    .M${c4}OO${c1}M${c3}ssssssssssssssssss${c2}dd${c1}M-    .-o${c3}s${c4}OOOOOOOOOOOO${c1}Mo',
      '    .MMMM${c3}sssssssss${c2}dd${c1}M${c3}ssssss${c2}dd${c1}M-    MM${c3}s${c4}OOOOOOOOOOOOOO${c1}M:.',
      '   -=${c3}s${c1}MMM${c3}sssssssss${c1}MMMMM${c3}sss${c2}ddd${c1}M-  :=${c2}ddd${c4}OO${c3}s${c2}d${c3}ss${c4}OO${c3}s${c4}OOOOOO${c1}M-',
      '   +M${c3}ssss${c1}MM${c3}sssssss${c1}MMMMM${c3}s${c2}ddd${c1}MM${c4}O${c1}o+ -M${c2}ddd${c3}ss${c2}ddd${c3}s${c2}ddd${c4}OOOOOOO${c1}o+',
      '    ${c2}.d${c3}ss${c2}d${c3}sssssssss${c1}MMM${c2}dd${c3}s${c2}ddd${c1}MM${c4}OOO${c1}MM${c2}ddddddddddddd${c3}s${c4}OOO${c2}dd${c3}s${c1}MM',
      '   ${c3}:=${c1}MM${c3}ssss${c2}d${c3}ssssssssss${c2}dddd${c1}M${c4}OOOOOOO${c1}M${c2}dddddddddddddd${c4}O${c3}s${c2}dddd${c1}M',
      ' ${c3}.+${c4}OOO${c3}ss${c1}MMM${c2}d${c3}sssss${c2}dddddd${c1}MMM${c4}OOOOO${c3}s${c4}OOO${c1}M${c2}ddddddddddddddddddd${c1}M',
      '${c3}ss${c4}OOOOOO${c3}sss${c4}O${c1}MMMMMMMMMMM${c3}s${c4}OOOOOOOO${c3}s${c1}MMMM${c2}dddddddddddddddd${c1}MMM',
      '${c3}ss${c4}OOOOOOOOOOOOOOOOOOOOOOO${c3}s${c4}OOOOOOO${c1}MMMMM${c2}ddddddddddddd${c1}MMM+=',
      '${c3}:-${c1}M${c4}OO${c3}s${c4}OOOOOOOOOOOOOOO${c3}s${c4}OOOO${c3}s${c4}OOOO${c3}s${c1}MMMMMMMMMMMMMMMMMMMMMM-',
      ' .o${c4}OO${c3}s${c4}OOOOOOOOOOOOOOO${c3}ss${c4}OOO${c3}s${c4}OOOO${c1}M${c2}d${c1}MMMMMMMMMMMMMMMMMMMM..',
      '   -==${c4}oOOOOOOOOOOOOOO${c3}s${c4}OO${c3}ss${c4}OOO${c1}M${c2}ddddd${c1}MMMMMMMMMMMMMM${c2}d${c1}M+=',
      '      +M${c3}s${c4}OOOOOOOOOOO${c1}MMM${c3}s${c1}MM${c2}dddddddddd${c1}MMMMMMM${c2}d${c1}M${c2}dd${c1}MMM:.',
      '      .:o${c4}OO${c3}s${c4}OOO${c3}ss${c4}O${c1}MMM${c2}dd${c1}M${c2}ddd${c1}MM${c2}dddddddd${c1}MMMMMMoooo...',
      '         +MM${c4}OO${c3}s${c4}OO${c1}MMMM${c2}dddddd${c1}MM${c2}dddddddd${c1}M++++:',
      '         +M${c2}dd${c1}MMMMMMMM${c2}ddddd${c1}MMMM${c2}dddddd${c1}+-',
      '       .+${c2}dddddd${c1}M+.+MM${c3}sssss${c1}M${c2}dddddddd${c1}M-',
      '      +M${c2}dddddd${c1}M..MMM${c3}ssssss${c1}MMM${c2}d${c1}MM${c2}d${c1}o+',
      '      :=${c2}d${c1}MM${c2}d${c1}Mo-..M${c3}ssssss${c2}d${c1}o-------.',
      '       .......  ..+MMMMM-.',
    ],
  },
  snorlax: {
    dex: 143,
    colors: ['#505050', '#315A7B', '#E6C5AC', '#F6E6BD'],
    lines: [
      '                   ${c1}..          ..+${c2}dd${c1}=.',
      '                  -${c2}dd${c1}=-.     ..+${c2}ddddd${c1}=',
      '                 -${c2}ddddd${c1}o++++++${c2}dddddddd${c1}=.',
      '                 +${c2}dddddddddddddddddddddd${c1}=',
      '                .+${c2}ddddddddddd${c4}OOO${c1}MM${c2}ddddddd${c1}-.',
      '                =${c2}dd${c4}OOOO${c2}ddd${c4}OOOOOOOOO${c1}M${c2}dddddd${c1}-     ...:=.',
      '               .+${c3}s${c4}OOOOOOOOOOOOOOOOOO${c1}M${c2}ddddd${c1}+:    Mo+MM--=',
      '               =${c2}d${c4}OO${c1}M${c4}OOOOOOOOO${c1}M${c4}OOOOOOO${c1}M${c2}ddddd${c1}-  :+${c2}ddddd${c1}MMM',
      '    .-.=M--:   =${c2}d${c4}OOOOOOOOOOOOOOOOOOOO${c1}M${c2}dddd${c1}MM=+${c2}ddddddd${c1}MMM',
      '   .-MM${c2}ddd${c1}Mo.   =M${c4}OOO${c1}MM${c4}OOOO${c1}M${c4}O${c1}M${c4}OOOOOO${c1}M${c2}dddd${c1}MM${c2}dddddddddd${c1}MMo',
      '   :MM${c2}ddddddo${c1}=-..-${c2}d${c4}OOOOOOOOOOOOOOOO${c2}ddddddddddddddddddd${c1}+.',
      '   .+M${c2}dddddddddd+${c1}+MMM${c4}OOOOOOOOOOOOO${c2}ddddddddddddddddddd${c1}+.',
      '    .+${c2}dddddddddddddd${c1}M${c4}OOO${c3}ssss${c4}O${c3}s${c4}OOOOOOO${c1}M${c2}dddddddddddddd${c1}-.',
      '     .+${c2}dddddddddd${c1}M${c4}OOOOOOOOOOOOOOOOOOOOO${c1}M${c2}dddddddddd${c1}+.',
      '       .+${c2}dddddd${c4}OOOOOOOOOOOOOOOOOOOOOOOOOO${c1}M${c2}dddddddd${c1}o-.',
      '         .=+${c2}d${c1}M${c4}OOOOOOOOOOOOOOOOOOOOOOOOOOOO${c1}M${c2}ddddddd${c1}MMo.',
      '           .=${c4}OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO${c1}M${c2}dddd${c1}MMMMMo.',
      '          ..M${c4}OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO${c1}MMMMMMMMMM=.',
      '          .M${c4}OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO${c3}ss${c1}MMMMMMMMMM.',
      '          :M${c4}OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO${c3}sss${c1}MMMMMMMMMM+',
      '  .+=..+-.M${c3}ss${c4}OOOOOOOOOOOOOOOOOOOOOOOOOOO${c3}ssssss${c1}MMMMMMMMMM',
      '---M${c4}O${c1}MM${c4}O${c3}ss${c1}M${c3}ssss${c4}OOOOOOOOOOOOOOOOOOOOOO${c3}ssss${c1}MM${c3}sss${c1}MM${c3}s${c1}MMMMMMM',
      '-${c4}OO${c1}M${c4}OOO${c1}M${c3}s${c1}M${c4}O${c3}sssssss${c4}OOOOOOOOOOOOOO${c3}ssssssss${c1}M${c4}OO${c1}MMM${c3}s${c4}O${c3}s${c1}MMMMMMM',
      ' :M${c4}OOOOOOOOOO${c1}M${c3}ssssssssssssssssssssssss${c1}M${c4}OOOOOOOOO${c3}ss${c1}M${c4}O${c1}MMM+',
      ' .M${c4}O${c3}sssss${c4}OOOO${c3}s${c1}M${c3}sssssssssssssssssssss${c1}M${c4}OOOOOO${c3}sssssssss${c1}MMM.',
      ' ..MMMMM${c3}sssssss${c1}M${c3}sssssssssssssssssss${c1}M${c3}s${c4}OOO${c3}ssss${c1}MMM${c3}sssss${c1}MM:.',
      '   .MMMMM${c3}ssssss${c1}MMM${c3}sssssssssssssssss${c1}M${c4}OOOO${c3}ss${c1}MMMMMMM${c3}sss${c1}=.',
      '    .=oMMM${c3}sssss${c1}MM+++${c3}+sssssssssssssss${c1}M${c4}OO${c3}ss${c1}MMMMMMM${c3}sss${c1}-',
      '      .-=M${c3}sso${c1}=-...  .....-=======-...=${c3}sssss${c1}MMM${c3}sss${c1}-.',
      '         ....                         .==${c3}ssss${c1}==..',
    ],
  },
  mewtwo: {
    dex: 150,
    colors: ['#7B39B5', '#505050', '#837B9C', '#DED5E6'],
    lines: [
      '                ${c3}-${c4}OOO${c3}=.     -${c4}OOO${c3}+.         ${c1}..====:...',
      '                ${c3}:${c4}oOOO${c3}=::${c2}::${c3}:+${c4}OOO${c3}+.       ${c1}.=MMM+${c2}+${c1}++MM+${c2}.',
      '                 ${c3}=${c4}OOOOOOOO${c3}s${c4}OOOO${c2}:      ${c1}.:MMM${c2}:..  .${c1}.${c2}:${c1}MM${c2}-.',
      '                ${c3}.=s${c4}OOOOOOOOOOOO${c2}-${c3}.     ${c1}.MMM${c2}:        :${c1}MM${c2}-',
      '                ${c3}-s${c4}OOOOOOOOOOOOO${c2}d-     ${c1}+MM${c2}:          d${c1}M${c2}=.',
      '                -${c4}OOOOOOO${c2}d${c4}OOOOOO${c2}d${c3}s${c2}d:   d${c1}M${c2}d.         o${c1}MMM${c2}:',
      '                .+${c3}s${c4}OOOO${c2}d${c1}M${c4}OOOOOO${c2}+${c3}sso:  ${c2}d${c1}MM${c2}+        .o${c1}MMM${c2}d',
      '                 .o${c4}OOOOOOOOO${c2}d+::d${c3}s${c2}+.  :d${c1}MM${c2}-       +${c1}MMMM${c2}d',
      '                  ${c3}:${c2}:${c3}+s${c2}d==${c3}sss${c2}o:+d${c3}s${c2}o.   .=${c1}MMM${c2}-     :${c1}oMMM${c2}d.',
      '                   ${c3}-${c4}oOOO${c3}s${c4}OOOOOO${c2}d${c3}s${c2}o     .=${c1}MMM${c2}-    =${c1}MMMM${c2}-.',
      '              ${c3}..${c2}:=${c3}s${c2}d${c4}OOOOOOOO${c2}d${c3}ssss${c4}O${c2}=${c3}:${c2}.   .o${c1}MMM${c2}:    :++.',
      '    ${c3}:${c2}:.   ${c3}::${c2}:${c3}=${c4}+OOO${c3}s${c2}+${c4}OOO${c3}s${c4}OOO${c2}d${c3}s${c2}o==${c3}s${c4}OOO+${c2}+=..+d${c1}MM${c2}+.',
      '${c3}.-${c2}=${c3}ss${c4}OOOOOOOOO${c2}d+-...:d${c4}OO${c2}d${c3}sss${c2}+.  ..+d${c4}OOOOOOOO${c2}dd.',
      'd${c4}OOO${c2}d${c4}OOOOO${c2}=::.     .+${c4}OOO${c3}ssss${c2}=.   d${c4}OOOOOO${c3}ss${c2}dd${c1}M${c2}d.',
      '.===dd${c4}OO${c2}d=       .+o${c1}MMMMM${c3}ss${c2}d${c4}OO${c3}o${c2}=.=${c4}O${c2}ddd${c3}ssss${c2}d${c1}MM${c2}d.',
      '   -${c4}OO${c2}=.       ${c3}.+${c4}OO${c1}MMMMMMM${c4}OOOOO${c3}ss${c2}d${c1}MMMMM${c2}dd${c4}OOO${c2}d:',
      '    ..        ${c3}.+${c4}OOO${c1}MMMMMM${c2}d${c4}OOOOO${c3}sss${c1}MMMMMMMMMM=${c2}.',
      '              ${c3}.=${c4}OOO${c1}MMMMMM${c2}d${c4}OOOOO${c3}ssss${c1}MMMMMMM+${c2}:.',
      '               .=${c3}sss${c1}MMMMMMM${c3}ssssssss${c1}MMMMo${c2}+:',
      '                .:${c3}ssss${c2}d==${c1}MM${c2}dd${c3}ssssss${c2}d=...',
      '                  :d${c3}ss${c2}d.   :::::+${c3}sss${c2}+.',
      '                  =${c4}OO${c2}d-.         :${c3}sss${c2}-',
      '               ${c3}.${c2}:+${c4}OOO${c2}d:.         .-${c3}ss${c2}d',
      '           ${c3}.:=+${c4}+OOOO${c2}d${c4}O${c2}+.         +${c4}OOO${c3}s${c2}-',
      '          .o${c4}OOOOOOO${c2}-...         .d${c4}OOOO${c3}s${c2}-.',
      '           .:=+++-.            :${c4}OOOOOOOO${c2}+.',
      '                               .-${c4}O+${c2}:-${c4}OO+${c2}:.',
    ],
  },
} as const;

export type PokemonName = keyof typeof POKEMON;

export const DEFAULT_POKEMON: PokemonName = 'gengar';

/** Ordem da pokedex, que e como o comando lista. */
export const POKEMON_NAMES = Object.keys(POKEMON).sort(
  (a, b) => POKEMON[a as PokemonName].dex - POKEMON[b as PokemonName].dex,
) as PokemonName[];
